service: code-breakfast-dashboard-group-1
runtime: python
env: flex
entrypoint: python3 dash_app.py

runtime_config:
  python_version: 3.7

manual_scaling:
  instances: 1
  
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10