#TODO: Fill in the required parameters
service: code-breakfast-dashboard-group-1
runtime: python
env: flex
entrypoint: python3 dash_app.py

runtime_config:
  python_version: 3.7

manual_scaling: #We could also use automatic_scaling, to add more instances if our server utilization surpasses a given threshold
  instances: 1
  
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10